name: Manual release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New semver version without cdp suffix"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Test build before release
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Read protocol version
        uses: pCYSl5EDgo/cat@master
        id: protocol-version
        with:
          path: protocol/version.txt
          trim: true

      - name: Compute release tag (with protocol version)
        run: echo "tag=${{ inputs.version }}-${{ steps.protocol-version.outputs.text }}" >> $GITHUB_OUTPUT
        id: compute-tag

      - name: Generate Change Log
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: generateChangelog -Pversion=${{ steps.compute-tag.outputs.tag }}

      - name: Commit and Push Change Log
        id: changelog-commit
        run: |
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git add CHANGELOG.md
          git commit -m "Version ${{ steps.compute-tag.outputs.tag }}"
          git push
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Create Release and Tag
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_PAT }} # using personal token to trigger publish workflow
          tag_name: ${{ inputs.version }}
          target_commitish: ${{ steps.changelog-commit.outputs.sha }}
          body_path: build/reports/changelog/latest-release-body.md
