name: Manual release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New semver version without cdp suffix"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Test build before release
        uses: burrunan/gradle-cache-action@v1
        with:
          # jobs with different JDK versions can't share caches
          job-id: jdk11
          arguments: build

      - name: Read protocol version
        uses: pCYSl5EDgo/cat@master
        id: protocol-version
        with:
          path: protocol/version.txt
          trim: true

      - name: Compute release tag (with protocol version)
        run: echo "::set-output name=tag::${{ github.event.inputs.version }}-${{ steps.protocol-version.outputs.text }}"
        id: compute-tag

      - name: Generate Change Log
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: generateChangelog -Pversion=${{ github.event.inputs.version }}

      - name: Commit and Push Change Log
        id: changelog-commit
        run: |
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git add CHANGELOG.md
          git commit -m "Version ${{ steps.compute-tag.outputs.tag }}"
          git push
          echo "::set-output name=sha::$(git rev-parse HEAD)"

      - name: Create Release and Tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} # using personal token to trigger publish workflow
        with:
          tag_name: ${{ steps.compute-tag.outputs.tag }}
          release_name: ${{ steps.compute-tag.outputs.tag }}
          commitish: ${{ steps.changelog-commit.outputs.sha }}
