name: Manual release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "New semver version without cdp suffix"
        required: true

jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # Docker is not installed on GitHub's MacOS hosted workers due to licensing issues
      - name: Setup docker (missing on MacOS)
        if: runner.os == 'macos'
        run: |
          brew install docker
          colima start
          
          # For testcontainers to find the Colima socket
          # https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running
          sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock

      - name: Compute full version (with protocol version)
        run: echo "fullVersion=${{ inputs.version }}-$(cat protocol/version.txt)" >> $GITHUB_OUTPUT
        id: compute-version

      # We don't just 'build' here because we want to test KDoc generation and publication mechanism too
      - name: Test local publish before release
        uses: gradle/gradle-build-action@v2
        env:
          # GPG keys for signing plugin (sign maven artifacts)
          # see https://docs.gradle.org/current/userguide/signing_plugin.html#sec:in-memory-keys
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SECRET_ASCII_ARMORED }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSWORD }}
        with:
          arguments: publishToMavenLocal

      - name: Generate Change Log
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: generateChangelog -Pversion=${{ steps.compute-version.outputs.fullVersion }}

      - name: Commit and Push Change Log
        id: changelog-commit
        run: |
          git add CHANGELOG.md
          git commit -m "Version ${{ steps.compute-version.outputs.fullVersion }}"
          git push
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Create Release and Tag
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.compute-version.outputs.fullVersion }}
          target_commitish: ${{ steps.changelog-commit.outputs.sha }}
          body_path: build/reports/changelog/latest-release-body.md

      # The publishToSonatype task and the repository release need to be in the same Gradle call
      # so that the closeAndRelease task knows which staging repository was created by publishToSonatype
      - name: Build and publish to OSS Sonatype and then Maven Central
        uses: gradle/gradle-build-action@v2
        env:
          # GPG keys for signing plugin (sign maven artifacts)
          # see https://docs.gradle.org/current/userguide/signing_plugin.html#sec:in-memory-keys
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SECRET_ASCII_ARMORED }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PASSWORD }}
          # Credentials implicitly read by the gradle-nexus-publish-plugin
          # https://github.com/gradle-nexus/publish-plugin#publishing-to-maven-central-via-sonatype-ossrh
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_USER_TOKEN }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_KEY }}
        with:
          arguments: |
            publishToSonatype
            closeAndReleaseSonatypeStagingRepository
            -Pversion=${{ steps.compute-version.outputs.fullVersion }}