name: Daily protocol updates
on:
  workflow_dispatch: { } # to allow manual trigger
  schedule:
    # Every night at 4am
    - cron: "0 4 * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # for Gradle, as setup-kotlin action only brings JDK 8
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Gradle build cache
        uses: actions/cache@v2.1.1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-build-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-build-

      - name: Gradle wrapper cache
        uses: actions/cache@v2.1.1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}

      - name: Update protocol
        run: ./gradlew updateProtocolDefinitions

      - name: Read protocol version
        uses: pCYSl5EDgo/cat@master
        id: version
        with:
          path: protocol/version.txt
          trim: true

      - name: Update public ABI descriptors
        run: ./gradlew apiDump

      - name: Create pull-request
        uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "protocol-update"
          author: "Protocol Update Workflow <protocol-updater@users.noreply.github.com>"
          commit-message: "Update to Chrome DevTools Protocol version ${{ steps.version.outputs.text }}"
          title: "Update to Chrome DevTools Protocol version ${{ steps.version.outputs.text }}"
          body: |
            This PR updates the protocol definitions (under `protocol/`) to the latest version found in
            [the `devtools-protocol` github repo](https://github.com/ChromeDevTools/devtools-protocol/tree/master/json).

            The ABI descriptors (under `api/`) are also updated to reflect the changes in the generated code.
